const Map<String, String> arSa = {
  'app_name': 'أوت ميد',
  'medical_supply_simplified': 'المستلزمات الطبية ببساطة',
  'skip': 'تخطي',
  'continue': 'متابعة',
  'get_started': 'ابدأ الآن',
  'onboarding_title_1': 'اعثر على مورّدين طبيين موثوقين',
  'onboarding_body_1':
      'احصل على مجموعة واسعة من المورّدين الموثوقين والمنتجات الطبية عالية الجودة في مكان واحد.',
  'onboarding_title_2': 'اطلب فوراً وبأمان',
  'onboarding_body_2': 'قدّم الطلبات ببضع نقرات مع دفع آمن وشفافية كاملة.',
  'onboarding_title_3': 'تتبّع كل طلب في الوقت الفعلي',
  'onboarding_body_3': 'تابع كل خطوة مع تتبّع فوري وتوصيل موثوق إلى مستشفاك.',
  'welcome_back': 'مرحباً بعودتك',
  'login_subtitle': 'سجّل الدخول للمتابعة إلى السوق',
  'email': 'البريد الإلكتروني',
  'password': 'كلمة المرور',
  'forgot_password': 'نسيت كلمة المرور؟',
  'sign_in': 'تسجيل الدخول',
  'buyer': 'المشتري',
  'supplier': 'المورّد',
  'continue_as': 'المتابعة بصفة',
  'demo_role_hint': 'تبديل الدور التجريبي',
  'no_account': 'ليس لديك حساب؟',
  'create_account': 'إنشاء حساب',
  'join_outmed': 'انضم إلى سوق OutMed',
  'buy_sell_medical': 'اشترِ وبِع المستلزمات الطبية الموثوقة',
  'sign_up_email': 'المتابعة بالبريد الإلكتروني',
  'sign_up_google': 'المتابعة باستخدام Google',
  'sign_up_apple': 'المتابعة باستخدام Apple',
  'already_account': 'لديك حساب بالفعل؟',
  'log_in': 'تسجيل الدخول',
  'select_profile': 'اختر نوع الملف',
  'healthcare_facility': 'منشأة رعاية صحية',
  'profile_type_hint': 'اختر طريقة استخدام مؤسستك لـ OutMed',
  'verify_email': 'تحقق من بريدك الإلكتروني',
  'verify_email_body':
      'أدخل الرمز المكوّن من ستة أرقام المرسل إلى بريدك الإلكتروني.',
  'verification_code': 'رمز التحقق',
  'verify': 'تحقق',
  'reset_password': 'إعادة تعيين كلمة المرور',
  'send_code': 'إرسال رمز التحقق',
  'create_new_password': 'إنشاء كلمة مرور جديدة',
  'password_hint': 'استخدم كلمة مرور مختلفة عن كلمات المرور السابقة.',
  'confirm_password': 'تأكيد كلمة المرور',
  'verified': 'تم التحقق',
  'verified_body': 'تم التحقق من حسابك وهو جاهز للاستخدام.',
  'login_account': 'تسجيل الدخول إلى حسابك',
  'home': 'الرئيسية',
  'categories': 'الفئات',
  'cart': 'السلة',
  'messages': 'الرسائل',
  'profile': 'الملف الشخصي',
  'orders': 'الطلبات',
  'catalog': 'الكتالوج',
  'inventory': 'المخزون',
  'hello': 'مرحباً',
  'find_supplies': 'اعثر على المستلزمات التي تحتاجها منشأتك',
  'reliable_medical_supplies': 'مستلزمات طبية موثوقة',
  'search_products': 'البحث عن المنتجات',
  'featured_products': 'منتجات مميزة',
  'top_suppliers': 'أفضل المورّدين',
  'view_all': 'عرض الكل',
  'all_products': 'جميع المنتجات',
  'all': 'الكل',
  'diagnostic': 'التشخيص',
  'surgical': 'الجراحة',
  'ppe': 'السلامة والوقاية',
  'dental': 'الأسنان',
  'verified_supplier': 'مورّد موثّق',
  'in_stock': 'متوفر',
  'out_of_stock': 'غير متوفر',
  'sar': 'ر.س',
  'product_information': 'معلومات المنتج',
  'suppliers': 'المورّدون',
  'select_quantity': 'اختر الكمية',
  'add_to_cart': 'أضف إلى السلة',
  'added_to_cart': 'تمت الإضافة إلى السلة',
  'size': 'المقاس',
  'your_cart': 'سلة التسوق',
  'subtotal': 'المجموع الفرعي',
  'delivery': 'التوصيل',
  'vat': 'الضريبة',
  'price_includes_vat': 'السعر شامل الضريبة',
  'items': 'عناصر',
  'products': 'منتجات',
  'days': 'أيام',
  'minimum_short': 'الحد الأدنى',
  'total': 'الإجمالي',
  'checkout': 'إتمام الشراء',
  'place_order': 'تأكيد الطلب',
  'delivery_address': 'عنوان التوصيل',
  'payment_method': 'طريقة الدفع',
  'order_placed': 'تم إنشاء الطلب بنجاح',
  'continue_shopping': 'متابعة التسوق',
  'track_order': 'تتبع الطلب',
  'order_details': 'تفاصيل الطلب',
  'confirmed': 'مؤكد',
  'preparing': 'قيد التجهيز',
  'ready_for_pickup': 'جاهز للاستلام',
  'in_transit': 'قيد التوصيل',
  'delivered': 'تم التسليم',
  'recent_orders': 'الطلبات الأخيرة',
  'my_orders': 'طلباتي',
  'no_orders': 'لا توجد طلبات بعد',
  'pending_confirmation': 'بانتظار تأكيد المورّد',
  'confirm_order': 'تأكيد الطلب',
  'move_to_in_transit': 'تحويل إلى قيد التوصيل',
  'mark_delivered': 'تأكيد التسليم',
  'new_message': 'رسالة جديدة',
  'type_message': 'اكتب رسالة',
  'account': 'الحساب',
  'company_profile': 'ملف الشركة',
  'addresses': 'العناوين',
  'payment_methods': 'طرق الدفع',
  'language': 'اللغة',
  'notifications': 'الإشعارات',
  'help_support': 'المساعدة والدعم',
  'terms_conditions': 'الشروط والأحكام',
  'logout': 'تسجيل الخروج',
  'english': 'الإنجليزية',
  'arabic': 'العربية',
  'choose_language': 'اختر اللغة',
  'supplier_catalog': 'كتالوج المورّد',
  'manage_offers': 'إدارة عروض المنتجات',
  'add_product_offer': 'إضافة عرض منتج',
  'search_before_create': 'ابحث في الكتالوج قبل إنشاء منتج',
  'select_master_product_hint':
      'يجب على المورّد اختيار منتج رئيسي موجود أولاً.',
  'search_catalog': 'البحث في الكتالوج الرئيسي',
  'product_exists': 'المنتج موجود مسبقاً',
  'select_product': 'اختر المنتج',
  'create_new_product': 'إنشاء منتج جديد',
  'no_product_found': 'لم يتم العثور على منتج مطابق',
  'create_only_if_missing': 'أنشئه فقط إذا لم تتم إضافته من قبل.',
  'canonical_product': 'معلومات المنتج الرئيسي',
  'canonical_locked': 'يتم قفل الاسم والصورة والمعلومات الرئيسية بعد الإنشاء.',
  'offer_information': 'معلومات عرضك',
  'supplier_editable_fields':
      'يمكن للمورّد تغيير السعر والمخزون ووصف العرض فقط.',
  'price': 'السعر',
  'stock': 'المخزون',
  'description': 'الوصف',
  'minimum_order': 'الحد الأدنى للطلب',
  'preparation_days': 'أيام التجهيز',
  'save_offer': 'حفظ العرض',
  'update_offer': 'تحديث العرض',
  'offer_saved': 'تم حفظ العرض بنجاح',
  'product_name': 'اسم المنتج',
  'product_image': 'صورة المنتج',
  'upload_product_image': 'رفع صورة المنتج',
  'change_product_image': 'تغيير صورة المنتج',
  'category': 'الفئة',
  'brand': 'العلامة التجارية',
  'manufacturer': 'الشركة المصنعة',
  'sku_reference': 'الرمز / المرجع',
  'model_number': 'رقم الموديل / المرجع',
  'specifications': 'المقاس / المواصفات',
  'pack_size': 'حجم العبوة',
  'barcode_udi': 'الباركود / UDI',
  'country_of_origin': 'بلد المنشأ',
  'storage_requirements': 'متطلبات التخزين',
  'product_documents': 'مستندات المنتج',
  'upload_product_document': 'رفع مستند المنتج',
  'image_required': 'اختر صورة المنتج',
  'product_created': 'تم إنشاء المنتج الرئيسي',
  'duplicate_product': 'هذا المنتج موجود. اختره من البحث.',
  'supplier_orders': 'طلبات المورّد',
  'new_orders': 'طلبات جديدة',
  'mark_preparing': 'بدء التجهيز',
  'mark_ready': 'جاهز للاستلام',
  'offer_count': 'عروض',
  'active': 'نشط',
  'low_stock': 'مخزون منخفض',
  'edit_offer': 'تعديل العرض',
  'delete_offer': 'حذف العرض',
  'delete': 'حذف',
  'cancel': 'إلغاء',
  'confirm_delete_offer':
      'هل تريد حذف هذا العرض من الكتالوج؟ سيبقى المنتج الرئيسي متاحاً.',
  'offer_deleted': 'تم حذف العرض',
  'buy_again': 'اشترِ مجدداً',
  'order_history': 'سجل الطلبات',
  'empty_orders_hint': 'ستظهر طلباتك السابقة هنا.',
  'offer_unavailable': 'هذا العرض لم يعد متاحاً.',
  'role_changed': 'تم تغيير الدور',
  'buyer_login': 'دخول المشتري',
  'supplier_login': 'دخول المورّد',
  'registration': 'التسجيل',
  'company_information': 'معلومات الشركة',
  'organization_information': 'معلومات المؤسسة',
  'business_address': 'عنوان المنشأة',
  'country': 'الدولة',
  'region': 'المنطقة',
  'full_address': 'العنوان الكامل',
  'postal_code': 'الرمز البريدي',
  'company_type': 'نوع الشركة',
  'vat_number': 'الرقم الضريبي',
  'bank_name': 'اسم البنك',
  'bank_account_holder': 'اسم صاحب الحساب البنكي',
  'year_established': 'سنة التأسيس',
  'number_employees': 'عدد الموظفين',
  'company_website': 'الموقع الإلكتروني للشركة',
  'company_name': 'اسم الشركة',
  'commercial_registration': 'رقم السجل التجاري',
  'city': 'المدينة',
  'primary_account_manager': 'مدير الحساب الرئيسي',
  'full_name': 'الاسم الكامل',
  'mobile_number': 'رقم الجوال',
  'job_title': 'المسمى الوظيفي',
  'documents': 'المستندات',
  'upload_documents': 'رفع المستندات المطلوبة',
  'payment_information': 'معلومات الدفع',
  'iban': 'رقم الآيبان',
  'accept_terms': 'أوافق على الشروط والأحكام الخاصة بالدور',
  'submit_registration': 'إرسال التسجيل',
  'registration_submitted': 'تم إرسال التسجيل لموافقة الإدارة',
  'next': 'التالي',
  'back': 'السابق',
  'required_field': 'هذا الحقل مطلوب',
  'invalid_email': 'أدخل بريداً إلكترونياً صالحاً',
  'supplier_profile': 'ملف المورّد',
  'about_supplier': 'عن المورّد',
  'message_supplier': 'مراسلة المورّد',
  'years': 'سنوات',
  'reviews': 'التقييمات',
  'chat': 'المحادثة',
  'update_stock': 'تحديث المخزون',
  'current_stock': 'المخزون الحالي',
  'new_stock_quantity': 'كمية المخزون الجديدة',
  'stock_updated': 'تم تحديث المخزون بنجاح',
  'good_evening': 'مساء الخير',
  'shop_now': 'تسوق الآن',
  'shop_by_category': 'تسوق حسب الفئة',
  'all_categories': 'كل الفئات',
  'more': 'المزيد',
  'search_placeholder': 'ابحث عن المنتجات والمستلزمات...',
  'trusted_partner': 'شريكك الموثوق لـ',
  'banner_heading': 'المستلزمات الطبية',
  'banner_subtext':
      'منتجات عالية الجودة، مورّدون موثوقون. توصيل في الوقت المحدد.',
  'remember_me': 'تذكرني',
  'healthcare_facility_hint': 'المستشفيات والعيادات والمختبرات والصيدليات',
  'suppliers_hint': 'المستلزمات الطبية والمصنّعون والموزّعون',
  'search_messages': 'ابحث في الرسائل والمورّدين',
  'unread': 'غير مقروء',
  'order_filter': 'طلب',
  'my_profile': 'ملفي الشخصي',
  'edit_profile': 'تعديل الملف',
  'security': 'الأمان',
  'logout_confirm': 'تسجيل الخروج من التطبيق؟',
  'shipping': 'الشحن',
  'proceed_checkout': 'المتابعة إلى الدفع',
  'verified_cart_banner': 'جميع العناصر من مورّدين موثوقين.',
  'units': 'وحدات',
  'last_updated': 'آخر تحديث',
  'unit_type': 'نوع الوحدة',
  'set_new_quantity': 'تعيين كمية جديدة',
  'all_orders': 'كل الطلبات',
  'pending': 'قيد الانتظار',
  'accepted': 'مقبول',
  'passwords_mismatch': 'كلمتا المرور غير متطابقتين',
  'privacy_agree': 'أوافق على سياسة الخصوصية الخاصة بـ OutMed',
  'code_sent': 'تم إرسال رمز التحقق',
  'medicine': 'الأدوية',
  'emergency_care': 'الرعاية الطارئة',
  'laboratory': 'المختبر',
  'cardiology': 'أمراض القلب',
  'surgical_instruments': 'الأدوات الجراحية',
  'positive_feedback': 'تقييم إيجابي',
  'fast_delivery': 'توصيل سريع',
  'secure_payment': 'دفع آمن',
  'easy_returns': 'إرجاع سهل',
  'support_24': 'دعم على مدار الساعة',
  'about_healthcare':
      'HealthCare Supplies مورّد طبي موثوق يخدم المستشفيات والعيادات في المنطقة.',
  'about_marsh':
      'Marsh Medical يوفّر منتجات جراحية وتشخيصية مع تنفيذ موثوق ومراقبة جودة.',
  'dashboard': 'لوحة التحكم',
  'inventory_subtitle': 'أدِر منتجاتك ومستويات المخزون.',
  'business_today': 'هذا ما يحدث في عملك اليوم',
  'todays_orders': 'طلبات اليوم',
  'todays_revenue': 'إيرادات اليوم',
  'pending_orders': 'طلبات معلّقة',
  'add_product': 'إضافة منتج',
  'add_new_product': 'إضافة منتج جديد',
  'manage_inventory': 'إدارة المخزون',
  'manage_orders': 'إدارة الطلبات',
  'view_details': 'عرض التفاصيل',
  'low_stock_alert': 'تنبيه مخزون منخفض',
  'only_left': 'متبقي @count فقط في المخزون',
  'total_products': 'إجمالي المنتجات',
  'added_on': 'أُضيف في',
  'sku': 'الرمز',
  'shipped': 'تم الشحن',
  'all_products_filter': 'كل المنتجات',
  'product_count_label': '@count منتجات',
};
