const Map<String, String> enUs = {
  'app_name': 'OutMed',
  'medical_supply_simplified': 'Medical supply, simplified',
  'skip': 'Skip',
  'continue': 'Continue',
  'get_started': 'Get started',
  'onboarding_title_1': 'Find trusted medical suppliers',
  'onboarding_body_1':
      'Access a wide range of verified suppliers and high-quality medical products in one place.',
  'onboarding_title_2': 'Order instantly and securely',
  'onboarding_body_2':
      'Place orders in just a few taps with secure payments and complete transparency.',
  'onboarding_title_3': 'Track every order in real time',
  'onboarding_body_3':
      'Stay updated at every step with real-time tracking and reliable delivery to your hospital.',
  'welcome_back': 'Welcome back',
  'login_subtitle': 'Sign in to continue to your marketplace',
  'email': 'Email address',
  'password': 'Password',
  'forgot_password': 'Forgot password?',
  'sign_in': 'Sign in',
  'buyer': 'Buyer',
  'supplier': 'Supplier',
  'continue_as': 'Continue as',
  'demo_role_hint': 'Demo role switch',
  'no_account': 'Don’t have an account?',
  'create_account': 'Create account',
  'join_outmed': 'Join the OutMed marketplace',
  'buy_sell_medical': 'Buy and sell trusted medical supplies',
  'sign_up_email': 'Continue with email',
  'sign_up_google': 'Continue with Google',
  'sign_up_apple': 'Continue with Apple',
  'already_account': 'Already have an account?',
  'log_in': 'Log in',
  'select_profile': 'Select profile',
  'healthcare_facility': 'Healthcare facility',
  'profile_type_hint': 'Choose how your organization will use OutMed',
  'verify_email': 'Verify your email address',
  'verify_email_body': 'Enter the six-digit code sent to your email address.',
  'verification_code': 'Verification code',
  'verify': 'Verify',
  'reset_password': 'Reset password',
  'send_code': 'Send verification code',
  'create_new_password': 'Create new password',
  'password_hint': 'Use a password different from previously used passwords.',
  'confirm_password': 'Confirm password',
  'verified': 'Verified',
  'verified_body': 'Your account is verified and ready to use.',
  'login_account': 'Login to your account',
  'home': 'Home',
  'categories': 'Categories',
  'cart': 'Cart',
  'messages': 'Messages',
  'profile': 'Profile',
  'orders': 'Orders',
  'catalog': 'Catalog',
  'inventory': 'Inventory',
  'hello': 'Hello',
  'find_supplies': 'Find the supplies your facility needs',
  'reliable_medical_supplies': 'Reliable medical supplies',
  'search_products': 'Search products',
  'featured_products': 'Featured products',
  'top_suppliers': 'Top suppliers',
  'view_all': 'View all',
  'all_products': 'All Products',
  'all': 'All',
  'diagnostic': 'Diagnostic',
  'surgical': 'Surgical',
  'ppe': 'PPE & Safety',
  'dental': 'Dental',
  'verified_supplier': 'Verified supplier',
  'in_stock': 'In stock',
  'out_of_stock': 'Out of stock',
  'sar': 'SAR',
  'product_information': 'Product information',
  'suppliers': 'Suppliers',
  'select_quantity': 'Select quantity',
  'add_to_cart': 'Add to cart',
  'added_to_cart': 'Added to cart',
  'size': 'Size',
  'your_cart': 'Your cart',
  'subtotal': 'Subtotal',
  'delivery': 'Delivery',
  'vat': 'VAT',
  'price_includes_vat': 'Price includes VAT',
  'items': 'items',
  'products': 'products',
  'days': 'days',
  'minimum_short': 'Min',
  'total': 'Total',
  'checkout': 'Checkout',
  'place_order': 'Place order',
  'delivery_address': 'Delivery address',
  'payment_method': 'Payment method',
  'order_placed': 'Order placed successfully',
  'continue_shopping': 'Continue shopping',
  'track_order': 'Track order',
  'order_details': 'Order details',
  'confirmed': 'Confirmed',
  'preparing': 'Preparing',
  'ready_for_pickup': 'Ready for pickup',
  'in_transit': 'In transit',
  'delivered': 'Delivered',
  'recent_orders': 'Recent orders',
  'my_orders': 'My orders',
  'no_orders': 'No orders yet',
  'pending_confirmation': 'Pending supplier confirmation',
  'confirm_order': 'Confirm order',
  'move_to_in_transit': 'Mark in transit',
  'mark_delivered': 'Mark delivered',
  'new_message': 'New message',
  'type_message': 'Type a message',
  'account': 'Account',
  'company_profile': 'Company profile',
  'addresses': 'Addresses',
  'payment_methods': 'Payment methods',
  'language': 'Language',
  'notifications': 'Notifications',
  'help_support': 'Help & support',
  'terms_conditions': 'Terms & conditions',
  'logout': 'Log out',
  'english': 'English',
  'arabic': 'Arabic',
  'choose_language': 'Choose language',
  'supplier_catalog': 'Supplier catalog',
  'manage_offers': 'Manage your product offers',
  'add_product_offer': 'Add product offer',
  'search_before_create': 'Search the catalog before creating a product',
  'select_master_product_hint':
      'A supplier must select an existing master product first.',
  'search_catalog': 'Search master catalog',
  'product_exists': 'Product already exists',
  'select_product': 'Select product',
  'create_new_product': 'Create new product',
  'no_product_found': 'No matching product found',
  'create_only_if_missing': 'Create it only if it has never been added before.',
  'canonical_product': 'Master product information',
  'canonical_locked':
      'Name, image and master information are locked after creation.',
  'offer_information': 'Your offer information',
  'supplier_editable_fields':
      'Only price, stock and offer description can be changed by the supplier.',
  'price': 'Price',
  'stock': 'Stock',
  'description': 'Description',
  'minimum_order': 'Minimum order',
  'preparation_days': 'Preparation days',
  'save_offer': 'Save offer',
  'update_offer': 'Update offer',
  'offer_saved': 'Offer saved successfully',
  'product_name': 'Product name',
  'product_image': 'Product image',
  'upload_product_image': 'Upload product image',
  'change_product_image': 'Change product image',
  'category': 'Category',
  'brand': 'Brand',
  'manufacturer': 'Manufacturer',
  'sku_reference': 'SKU / reference',
  'model_number': 'Model / reference number',
  'specifications': 'Size / specifications',
  'pack_size': 'Pack size',
  'barcode_udi': 'Barcode / UDI',
  'country_of_origin': 'Country of origin',
  'storage_requirements': 'Storage requirements',
  'product_documents': 'Product documents',
  'upload_product_document': 'Upload product document',
  'image_required': 'Select a product image',
  'product_created': 'Master product created',
  'duplicate_product': 'This product already exists. Select it from search.',
  'supplier_orders': 'Supplier orders',
  'new_orders': 'New orders',
  'mark_preparing': 'Mark as preparing',
  'mark_ready': 'Mark ready for pickup',
  'offer_count': 'offers',
  'active': 'Active',
  'low_stock': 'Low stock',
  'edit_offer': 'Edit offer',
  'delete_offer': 'Delete offer',
  'delete': 'Delete',
  'cancel': 'Cancel',
  'confirm_delete_offer':
      'Remove this offer from your catalog? The master product will stay available.',
  'offer_deleted': 'Offer deleted',
  'buy_again': 'Buy again',
  'order_history': 'Order history',
  'empty_orders_hint': 'Your past orders will appear here.',
  'offer_unavailable': 'This offer is no longer available.',
  'role_changed': 'Role changed',
  'buyer_login': 'Buyer login',
  'supplier_login': 'Supplier login',
  'registration': 'Registration',
  'company_information': 'Company information',
  'organization_information': 'Organization information',
  'business_address': 'Business address',
  'country': 'Country',
  'region': 'Region',
  'full_address': 'Full address',
  'postal_code': 'Postal code',
  'company_type': 'Company type',
  'vat_number': 'VAT number',
  'bank_name': 'Bank name',
  'bank_account_holder': 'Bank account holder name',
  'year_established': 'Year established',
  'number_employees': 'Number of employees',
  'company_website': 'Company website',
  'company_name': 'Company name',
  'commercial_registration': 'Commercial registration number',
  'city': 'City',
  'primary_account_manager': 'Primary account manager',
  'full_name': 'Full name',
  'mobile_number': 'Mobile number',
  'job_title': 'Job title',
  'documents': 'Documents',
  'upload_documents': 'Upload required documents',
  'payment_information': 'Payment information',
  'iban': 'IBAN',
  'accept_terms': 'I accept the role-specific terms and conditions',
  'submit_registration': 'Submit registration',
  'registration_submitted': 'Registration submitted for admin approval',
  'next': 'Next',
  'back': 'Back',
  'required_field': 'This field is required',
  'invalid_email': 'Enter a valid email address',
  'supplier_profile': 'Supplier profile',
  'about_supplier': 'About supplier',
  'message_supplier': 'Message supplier',
  'years': 'Years',
  'reviews': 'Reviews',
  'chat': 'Chat',
  'update_stock': 'Update stock',
  'current_stock': 'Current stock',
  'new_stock_quantity': 'New stock quantity',
  'stock_updated': 'Stock updated successfully',
  'good_evening': 'Good evening',
  'shop_now': 'Shop now',
  'shop_by_category': 'Shop by category',
  'all_categories': 'All categories',
  'more': 'More',
  'search_placeholder': 'Search for products, supplies...',
  'trusted_partner': 'Your trusted partner for',
  'banner_heading': 'Medical Supplies',
  'banner_subtext': 'Quality products, verified suppliers. On-time delivery.',
  'remember_me': 'Remember me',
  'healthcare_facility_hint': 'Hospitals, clinics, laboratories and pharmacies',
  'suppliers_hint': 'Medical supplies, manufacturers and distributors',
  'search_messages': 'Search messages, suppliers',
  'unread': 'Unread',
  'order_filter': 'Order',
  'my_profile': 'My profile',
  'edit_profile': 'Edit profile',
  'security': 'Security',
  'logout_confirm': 'Logout from this app?',
  'shipping': 'Shipping',
  'proceed_checkout': 'Proceed to checkout',
  'verified_cart_banner': 'All items are from verified suppliers.',
  'units': 'Units',
  'last_updated': 'Last updated',
  'unit_type': 'Unit type',
  'set_new_quantity': 'Set new quantity',
  'all_orders': 'All orders',
  'pending': 'Pending',
  'accepted': 'Accepted',
  'passwords_mismatch': 'Passwords do not match',
  'privacy_agree': 'I agree to OutMed Privacy Policy',
  'code_sent': 'Verification code sent',
  'medicine': 'Medicine',
  'emergency_care': 'Emergency care',
  'laboratory': 'Laboratory',
  'cardiology': 'Cardiology',
  'surgical_instruments': 'Surgical instruments',
  'positive_feedback': 'Positive feedback',
  'fast_delivery': 'Fast delivery',
  'secure_payment': 'Secure payment',
  'easy_returns': 'Easy returns',
  'support_24': '24/7 Support',
  'about_healthcare':
      'HealthCare Supplies is a verified medical distributor serving hospitals and clinics across the region.',
  'about_marsh':
      'Marsh Medical supplies surgical and diagnostic products with reliable fulfillment and quality control.',
  'dashboard': 'Dashboard',
  'inventory_subtitle': 'Manage your products and stock levels.',
  'business_today': "Here's what's happening with your business today",
  'todays_orders': "Today's orders",
  'todays_revenue': "Today's revenue",
  'pending_orders': 'Pending orders',
  'add_product': 'Add product',
  'add_new_product': 'Add new product',
  'manage_inventory': 'Manage inventory',
  'manage_orders': 'Manage orders',
  'view_details': 'View details',
  'low_stock_alert': 'Low stock alert',
  'only_left': 'Only @count left in stock',
  'total_products': 'Total products',
  'added_on': 'Added on',
  'sku': 'SKU',
  'shipped': 'Shipped',
  'all_products_filter': 'All products',
  'product_count_label': '@count Products',
};
